apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-pvc-0
  namespace: development-9fwpl
  labels:
    vm-selector: mysql-db
  annotations:
    csi.vsphere.volume-requested-topology: '[{"topology.kubernetes.io/zone":"zone-1"}]'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: vcf-wld1-cl01-optimal-datastore-default-policy-raid1