apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-frontend-backend
  namespace: portal-development-wxq79
spec:
  project: default
  source:
    repoURL: 'https://github.com/KBrookfield/customer-portal'
    targetRevision: main
    path: customer-portal/apps/web-frontend-backend
    directory:
      recurse: true
  destination:
    # This is critical: you want to deploy to the newly registered cluster
    # Use the cluster context name that Argo CD sees after registration
    name: 'portal-dev-cluster-01-admin@portal-dev-cluster-01'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Deploy after the cluster is registered
  syncWave: 2