apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-vm
  namespace: development-9fwpl
spec:
  project: default
  source:
    repoURL: 'https://github.com/KBrookfield/customer-portal'
    targetRevision: main
    path: customer-portal/apps/database-vm
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: development-9fwpl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Runs in parallel with customer-portal-vks
  syncWave: -1