apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: portal-dev-cluster-01
  namespace: development-vbynb
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    class: builtin-generic-v3.3.0
    version: v1.32.0---vmware.6-fips-vkr.2
    variables:
      - name: kubernetes
        value:
          certificateRotation:
            enabled: true
            renewalDaysBeforeExpiry: 90
      - name: vmClass
        value: best-effort-small
      - name: storageClass
        value: vcf-wld1-cl01-optimal-datastore-default-policy-raid1
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon, content-library=cl-5b0cda58bd7d8fb68
    workers:
      machineDeployments:
        - class: node-pool
          name: portal-dev-cluster-01-nodepool-y09r
          replicas: 2
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu, content-library=cl-5b0cda58bd7d8fb68