apiVersion: batch/v1
kind: Job
metadata:
  name: register-portal-dev-cluster-01
  namespace: portal-development-wxq79
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      containers:
      - name: register
        image: ""  # Runs in-cluster without pulling an image
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Waiting for kubeconfig to be available..."
            while ! kubectl get secret portal-dev-cluster-01-kubeconfig -n argocd -o jsonpath='{.data.value}' | base64 -d > /tmp/portal-dev-cluster-01-kubeconfig; do
              sleep 5
            done

            echo "Extracting correct context..."
            CONTEXT=$(kubectl config --kubeconfig=/tmp/portal-dev-cluster-01-kubeconfig view -o jsonpath='{.contexts[0].name}')

            echo "Registering portal-dev-cluster-01 in ArgoCD with context: $CONTEXT"
            argocd cluster add $CONTEXT --kubeconfig /tmp/portal-dev-cluster-01-kubeconfig
      restartPolicy: Never